🚀 Feature:
  - changed-files:
    - any-glob-to-any-file: 'src/routes/**'

🛡️ Middleware:
  - changed-files:
    - any-glob-to-any-file: 'src/middlewares/**'

⚙️ Config:
  - changed-files:
    - any-glob-to-any-file: 'src/config/**'

🗃️ Database:
  - changed-files:
    - any-glob-to-any-file: 'prisma/**'

📝 Documentation:
  - changed-files:
    - any-glob-to-any-file: '*.md'

🔧 CI:
  - changed-files:
    - any-glob-to-any-file: '.github/**'

📦 Dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - 'package.json'
      - 'package-lock.json'
